import Foundation

/// The app's version, and the single source of truth for it.
///
/// Swift rather than Info.plist, because the plist is GENERATED by `install.sh` and
/// a literal there cannot be read by the code that needs it. Same scheme AuthBar and
/// Murmur run; the divergence is only the name.
///
/// `install.sh` greps `current` out of this file, stamps both plist keys from it, and
/// then verifies the stamp landed. Bumping a release is ONE edit here.
///
/// The literal is deliberately on its own line in the simplest possible form
/// (`= "x.y.z"`), because a shell `sed` has to parse it. If that line is reformatted
/// the installer fails loudly rather than silently shipping the previous version.
enum StowVersion {

    /// Semantic version. Bump here and nowhere else.
    ///
    /// **Third number only, until there is a release.** Increment the patch digit and
    /// nothing else, one step at a time: `0.1.2`, `0.1.3`, `0.1.4`. Do NOT bump the
    /// minor digit for a release that adds capability, however substantial it feels
    /// while writing it. A version number that climbs quickly stops carrying
    /// information, and the release notes already say what changed.
    ///
    /// This instruction was already written here and was violated twice in one day:
    /// `0.2.1` became `0.3.0` for the hide feature, having earlier jumped `0.1.1` to
    /// `0.2.0`. Both were renumbered back onto the patch line, which nothing had
    /// shipped from, and `versionOnlyEverBumpsThePatchDigit` now enforces the rule
    /// rather than asking politely.
    ///
    /// Major essentially never for a personal menu bar tool.
    static let current = "0.1.23"

    /// The minor line this project stays on until it releases.
    ///
    /// Named so the enforcing test has something to compare against, and so raising it
    /// is a visible, deliberate edit rather than a digit changed in passing.
    static let preReleaseLine = "0.1"

    static let builderAttribution = "built by GSD-ai"

    /// Version plus the commit the running bundle was built from.
    ///
    /// The version comes from this constant so it is always present; the commit comes
    /// from Info.plist, since only the installer knows it. A `swift run` build shows
    /// the version alone rather than a stamp with an empty field.
    static var display: String {
        let commit = buildCommit
        return commit == "dev" ? current : "\(current) · \(commit.prefix(7))"
    }

    /// The commit this bundle was built from.
    ///
    /// Kept outside a SwiftUI View so version formatting stays nonisolated and usable
    /// from tests and command-line builds.
    static var buildCommit: String {
        let value = Bundle.main.object(forInfoDictionaryKey: "STCommit") as? String
        let trimmed = value?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return trimmed.isEmpty ? "dev" : trimmed
    }
}
